[package]
name = "php"
version = "0.1.1"
description = "PHP is a popular general-purpose scripting language that is especially suited to web development"
readme = "README.md"
repository = "https://github.com/wapm-packages/php"

[[module]]
name = "php"
source = "php.wasm"
abi = "emscripten"

[[command]]
name = "php"
module = "php"
